import localFont from "next/font/local";
import "./globals.css";
import { cn } from "@/lib/utils";

const harmonyOSSans = localFont({
  src: './fonts/HarmonyOS_Sans_SC_Regular.ttf',
  display: 'swap'
});

export const metadata = {
  title: "UNO++",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={cn(harmonyOSSans.className, "dark")}>{children}</body>
    </html>
  );
}
